name: DiscordSystem
author: ~jkoo
version: 1.0
main: main.java.org.matejko.discordsystem.DiscordPlugin
commands:
  signremove:
    description: Removes sign from server.
    usage: /signremove signID
    aliases: [sr]
    permission-message: You do not have permission to use this command.
permissions:
  signremove:
    description: Allows access to the /signremove command.
    default: op